version: '3.8'

services:
  app:
    build: .
    image: ws_marchand:dev
    ports:
      - "8082:8082"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/ws_marchand_g4
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passer